### ISSUE TITLE
Wiimote won't detect classic controller

### ISSUE THREAD

**Issue by jinwk00** [jloehr/HID-Wiimote#10]
My wiimote won't detect classic controller pro even though I plugged it in. Is there something wrong, or is it just me?

**Comment by jloehr** [comment]
Is it a original from Nintendo or a counterfeit one?
I had some issues that sometimes the extension controller was not correctly detected and activated. I then plugged it out and in again until it worked.

**Comment by jinwk00** [comment]
It is original, though.

**Comment by jinwk00** [comment]
And yes, I plugged in and out multiple times.

**Comment by larsiusprime** [comment]
What's the model number?

On Thu, Oct 22, 2015 at 8:57 PM, jinwk00 <notifications@github.com> wrote:

> And yes, I plugged in and out multiple times.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jloehr/HID-Wiimote/issues/10#issuecomment-150410119>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by jloehr** [comment]
Ok, when i tested the driver with my Classic Controller Pro it worked, so it is more likely that there is a problem with your Classic Controller Pro or Wii Remote. Do you have another Wii Remote to test the Classic Controller Pro with? I assume it is working properly when connected to a Wii or Wii U Console.
However i also had it sometimes, that my extension was constantly not properly detected (like 9 out of 10 times), so there is still a chance that you hardware is fine and my driver is acting up.

Anyway i am opening a new issue, that i should change the code, so that the driver constantly retries to detect the extension, when it fails. That might fix it, as well as the "plug it out and in again" issue. Thanks for you feedback.

**Comment by jinwk00** [comment]
I just tested with another wiimote. Didn't worked at all. Only worked as 'NES' Styled control.

**Comment by jloehr** [comment]
What do you mean by 'NES' Styled Control?
Can you elaborate what exactly is not working and what you have expected how it is going to work.

Currently you don't get any feedback when plugging in an extension. The button mapping just silently changes.

**Comment by jinwk00** [comment]
Basically wiimote holding in a vertical way. Also, the extension seems to not work with this driver eve though Wii recognizes. Moreover, my OS is Windows 8.1 K.

**Comment by jinwk00** [comment]
Connected controller 50 times. 2 times it detected. Closed.

**Comment by jloehr** [comment]
Ew, ok, i really need to fix that.
