### ISSUE TITLE
Rumble / Speaker / etc.

### ISSUE THREAD

**Issue by larsiusprime** [jloehr/HID-Wiimote#9]
Sorry to load you down with issues :)

I was wondering what the interface for accessing various features on the Wiimote where instead of *receiving* input from the device, you're *sending* input to the device. This includes rumble and the wiimote speaker. I imagine the first is much easier than the second.

Is this functionality possible with the driver?

**Comment by jloehr** [comment]
AFAIK Rumble is not supported by HID.

See http://www.usb.org/developers/hidpage/Hut1_12v2.pdf for the usage pages.

For the other features like Speaker and the LEDs (which are internally used for another purpose) there are some usage pages that may fit, but i think nobody uses them. Especially in their games. And i think DirectInput does not have support for anything like them as well.

**Comment by larsiusprime** [comment]
Ah well, that's okay then I guess. How do they do rumble on the X360 I wonder?

**Comment by jloehr** [comment]
The Xbox 360 Controllers have a different class driver (XUSB), that exposes a interface for the XInput API. So the communication with the device is proprietary (But i am working on that so my driver serves the XUSB class driver as well, see #4)

**Comment by programminghoch10** [comment]
Can you make it like that you can use the speaker as an audio output device and that the leds can do a little bit more than showing the connection status like batery status or something?

**Comment by jloehr** [comment]
Speaker or Sound Output is not part of the HID Specs, so that won't be implemented anytime soon.
Additional the Wiimote Speaker only supports certain Audio codecs, as well as those are not fully reverse engineered. So implementing such, would require a huge amount of work.

Regarding the LEDs it would be possible to provide an Output report, however no game excepts and therefore uses LEDs on a Gamepad. So they won't be used by anything, but programs specifically written for the Wiimote. The goal of this project is to make the Wiimote available as generic Gamepad and not to provide another API.

The Motion Plus Extension is kind of on my list. However it is just a three axis gyro sensor. Such gyro sensor reports angular motion, no orientation. So directly mapping the data to axes won't be useful. It would be only useful to make the orientation more accurate on the short term. Additionally the Motion Plus needs some additional care regarding activation, data reading and data passing, when another extension is connected. So currently it is not worth it, as there are more important tasks.
